### ISSUE TITLE
Consider including link to new member to-do list in navigation bar

### ISSUE THREAD

**Issue by joewie** [HIRO-group/HIRO-group.github.io#41]
It'll be easier for new members to find.

Alternatively, maybe we could just force the list to be the top item in the wiki regardless of dates.

**Comment by alecive** [comment]
Isn't it already the top item of the wiki? 

I'd wager against adding yet another item in the navbar because it is already too crowded imho. I haven't even added a "News" section yet! The more things we add, the higher horizontal resolution is needed to see all of them and the sooner the navbar is collapsed [which I'd like to avoid at least on desktop].

However, what we can do is to keep it in the news section in the homepage. Maybe there are ways to pin it to the top but I'm not sure.

**Comment by joewie** [comment]
It's the top item of the wiki now, but in the past it was pushed down when there was a more recent wiki article.

Considering the navbar space limitations, maybe pinning it to the top of the wiki might be the best solution? If there's a way to do it, that is.
